name: simple-action

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get install -y flex bison
    - name: build binary
      run: make -C build/
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: stv
        path: ./build/stv
  other:
    continue-on-error: true
    needs: build
    strategy:
      matrix:
        mode: [0,1,2,3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: stv
          path: ./build/
      - name: run stv with matrix val
        run: |
          cd build
          chmod +x ./stv
          ./stv --mode ${{ matrix.mode }}
  clean:
    needs: [build, other]
    runs-on: ubuntu-latest
    steps:
    - uses: geekyeggo/delete-artifact@v2
      with:
          name: stv