name: test-action

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install flex and bison
      run: sudo apt-get install -y flex bison
    - name: test
      run: echo $(locate libfl.a)
    - name: make
      run: |
        cd build
        make clean
        make
    - name: run script
      run: ./actiontest.sh
      shell: bash
    - name: upload output log
      uses: actions/upload-artifact@v3
      with:
        name: output-log-file
        path: output.log

